
name: Docker Build/Publish Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/shinobi
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Clone shinobi
        run: git clone https://gitlab.com/Shinobi-Systems/Shinobi.git /opt/shinobi

      - name: Get git sha short
        id: short
        working-directory: /opt/shinobi
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            SHINOBI_VERSION=${{ steps.short.outputs.sha_short }}
          platforms: linux/arm64,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}-${{ steps.short.outputs.sha_short }}
